version: '3'
services:
  nginx:
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/sites-enabled/app.conf:/etc/nginx/sites-enabled/app.conf:ro
      - .:/var/www/api
      - ./frontend/dist:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./docker/php-fpm/symfony.ini:/usr/local/etc/php/conf.d/symfony.ini:ro
      - ./docker/php-fpm/symfony.ini:/usr/local/etc/php-fpm.d/symfony.ini:ro
      - ./docker/php-fpm/symfony.pool.conf:/usr/local/etc/php-fpm.d/symfony.pool.conf:ro
      - .:/var/www/api
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

